name: e2e Test

on:
  push:
    branches:
      -  feature/add-tests

env:
  TEST_PROJECT: ./test_project
  EXAMPLE_REMOTE_HOST:
  REMOTE_USER:
  REMOTE_PORT:
  ARGS:
  SOURCE:
  TARGET:
  EXCLUDE: ''


jobs:
  host:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Host info
        run: |
          ls -l
          ip addr show
          whoami
      - name: 1. Create ssh keys
        run: |
          ssh-keygen -m PEM -t rsa -b 4096 -f "$HOME/.ssh/id_rsa" -N ""
        shell: bash
      - name: Create project file
        run: |
          mkdir $TEST_PROJECT && cd $TEST_PROJECT
          touch index.html
          date +"%Y-%m-%d %H:%M:%S,%3N" >> index.html
          cat index.html
        shell: bash
